<<<<<<< HEAD
baseURL = "https://gerben31.github.io/myblog"
=======
baseURL = "https://gerben31.github.io/myblog/"
>>>>>>> ed9c789ea193d8e218b4e3a62f21607520d949c9
languageCode = "en-us"
title = "blog"
theme = "anubis"
pageinate = 30
publishDir = "docs"


[author] 
name = "tester"

[params]
author = "tester"
paginationSinglesPost = true
readMore = false 
style = "dark"

[[params.social]]
id = "12344"

[menu]

[[menu.main]]
identifier = "about"
name = "Aboud"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "tags"
name = "Tags"
weight = 1
